
const integration = {
    amazon: {
        id: 1,
        logo: '../assets/images/amazon_logo.svg',
        name: 'Amazon',
        type: 'Маркетплейсы',
        descr: 'Амазон — крупнейший маркетплейс в мире родом из США',
    },
    ebay: {
        id: 2,
        logo: '../assets/images/ebay.svg',
        name: 'Ebay',
        type: 'Маркетплейсы',
        descr: 'Ebay - cамый популярный интернет-аукцион в мире, работающий с 1995 года.',
    },
    etsy: {
        id: 3,
        logo: '../assets/images/etsy.svg',
        name: 'Etsy',
        type: 'Маркетплейсы',
        descr: 'Etsy - международная торговая площадка, специализирующаяся на продаже уникальных изделий.',
    },
    yandex: {
        id: 4,
        logo: '../assets/images/Yandex-market.svg',
        name: 'Яндекс.Маркет',
        type: 'Маркетплейсы',
        descr: 'Старейший российский маркетплейс потребительских товаров',
    },
    avito: {
        id: 5,
        logo: '../assets/images/avito.svg',
        name: 'Avito',
        type: 'Маркетплейсы',
        descr: 'Avito - самый популярный в России онлайн-сервис для продажи товаров, насчитывающий более 50 млн активных объявлений.',
    },
    pochtarossii: {
        id: 6,
        logo: '../assets/images/Russian_Post.svg',
        name: 'Почта России',
        type: 'Логистические интеграции',
        descr: 'Интеграция с сервисами Почты России для международной интернет-торговли. ',
    },
    dhl: {
        id: 7,
        logo: '../assets/images/DHL_Logo.svg',
        name: 'DHL',
        type: 'Логистические интеграции',
        descr: 'Модуль позволяет создать интеграцию с DHL, осуществляющей доставку грузов по всему миру.',
    },
    shiptor: {
        id: 8,
        logo: '../assets/images//shiptor.svg',
        name: 'Shiptor',
        type: 'Логистические интеграции',
        descr: 'Модуль позволяет сделать интеграцию со службой доставки Shiptor.',
    },
    bitriks: {
        id: 9,
        logo: '../assets/images/Bitrix24-logo-ru.svg',
        name: 'Битрикс-24',
        type: 'CRM / CMS',
        descr: 'Битрикс24 — российский сервис для управления бизнесом.',
    },
    bitrix1c: {
        id: 10,
        logo: '../assets/images/1c_bitrix_logo.svg',
        name: '1С-Битрикс',
        type: 'CRM / CMS',
        descr: '1С-Битрикс — российский сервис для управления бизнесом.',
    },
    retail: {
        id: 11,
        logo: '../assets/images/retail.svg',
        name: 'Retail-CRM',
        type: 'CRM / CMS',
        descr: 'Retail-CRM —  сервис для управления бизнесом.',
    },
    insales: {
        id: 12,
        logo: '../assets/images/inSales.svg',
        name: 'InSales',
        type: 'CRM / CMS',
        descr: 'InSales — сервис для управления бизнесом.',
    },
};